server:
  port: 8003

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.sxt.springcloud.entities
  mapper-locations: classpath:mybatis/mapper/**/*.xml

spring:
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.1.101:3306/cloudDB03 
    username: root
    password: hu820826
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
      
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      #defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-dept-8003
    prefer-ip-address: true
    
    
info:
  app.name: com.sxt.springcloud
  company.name: www.sxt.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$    